### ISSUE TITLE
sock.bind(address): Permission denied, requires elevated privileges on *NIX platform

### ISSUE THREAD

**Issue by coder3101** [ArjunInventor/AnyoneAI#1]
Ports below 1024 are considered "privileged" and can only be bound to with an equally privileged user like (root)

Anything above and including 1024 is "free to use" by anyone.

Due to this reason 
You need to do 
> sudo anyoneai 

Simply this

> anyoneai 

will throw a Permission denied error.

This is not preferred and only system services should be given elevated privileges. Since anyoneai is user based service for security and reliability it should run on usermode with some other port than 80. Say 8089 or something.

**Comment by coder3101** [comment]
@ArjunInventor better set some specific non-elevated default PORT for Anyoneai and allow user to choose their port of choice with some configuration settings. In that way if user chooses to run it on port 80, they will know to elevate the privilege.

A command line arguments parse would be good like, 

>sudo anyoneai --port=80

Runs on port 80, with elevated privileges

> anyoneai 

Runs on default port say 8089.

**Comment by arjuninv** [comment]
The issue has been fixed. The port has now been defaulted to 8089, and can be modified with the command line argument --port

Thanks for reporting the issue!
